<!--
 * @Author: your name
 * @Date: 2020-06-27 11:06:07
 * @LastEditTime: 2020-06-27 17:40:55
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: /learnNodeAgain/libs/异步编程.md
--> 
# 异步编程
NodeJS 最大的卖点 —— 事件机制和异步I/O,对开发者并不是透明的，开发者需要按异步方式编写代码才用的上这个卖点。而这一点也遭到一些 NodeJS 反对者的抨击，但不管怎样。异步编程确实是 NodeJS 最大的特点，没有掌握异步编程就不能说真正学会了 NodeJS
## 回调
在代码中，异步编程的直接体现就是回调，异步编程依托于回调来实现，但不能说使用了回调后程序就异步化了，案例：
```
function heavyCompute(n, callback){
    var count = 0
        i, j;
    
    for(i = n;i > 0; --i){
        for(j = n;j > 0; --j){
            count += 1;
        }
    }

    callback(count);
}

heavyCompute(10000, count => {
    console.log(count);
});

console.log('hello');

------ console -----------------------

100000000
hello
```
回调任然先于后续代码执行，JS本身是单线程运行的，不可能在一段代码还未结束运行时去运行别的代码，因此也就不存在异步执行的概念。</br>
但是如果某个函数做的事情是创建一个别的线程或进程，并与JS主线程并行的做一些事情，并在事情做完后通知主线程，那情况又不一样了，看示例：
```
setTImeout(() => {
    console.log('world');
}, 1000);
console.log('hello');

------ console -----------------------

hello
world
```
该示例可以看到，回调函数 `后于` 后续代码执行。如同上边所说，JS本身是 `单线程` 的，无法异步执行，因此我们可以认为 `setTimeout` 这类 JS规范之外 的由 运行环境 提供的特殊函数 做的事情是创建一个 `平行线程`后 立即返回，让JS主进程可以 接着 执行后续代码，并在收到平行进程的通知后, 再执行回调函数。除了 `setTimeout`、`setInterval` 这些常见的，这类函数还包括NodeJS提供的诸如 `fs.readFile` 之类的异步API。</br>

另外，我们仍然回到JS是 `单线程运行` 的这个事实上，这决定了JS在 `执行完` 一段代码之前，`无法执行` 包括 `回调函数` 在内的 `别的代码`。也就是说，即使 `平行线程` 完成工作了，`通知` JS主线程 `执行回调函数` 了，回调函数也要 `等到JS主线程空闲时` 才能开始执行，看示例：
```
function heavyCompute(n){
    var count = 0
        i, j;
    
    for(i = n;i > 0; --i){
        for(j = n;j > 0; --j){
            count += 1;
        }
    }
}

var t = new Date();
setTImeout(() => {
    console.log(new Date() - t);
}, 1000);

heavyCompute(50000);

------ console -----------------------

8250
```
可以看到，本来应该在 `1秒后` 被调用的回调函数因为 `主线程忙` 于运行其他代码，实际执行时间被大幅延迟。

## 代码设计模式
异步编程有很多特有的代码设计模式，为了实现相同的功能，使用同步方式和异步方式编写的代码会有很大差异，以下分别介绍一些常见的模式
### 函数返回值
使用一个函数的输出作为另一个函数的输入是很常见的需求，在同步方式下一般按以下方式编写代码：
```
var output = fn1(fn2('input'));
// So something else ...
```
而在异步方式下，由于函数执行结果不是通过返回值，而是通过回调函数传递，因此一般按以下方式编写代码
```
fn2('input', output2 => {
    fn1(output2, output1 => {
      // Do something ...  
    })
});
```
可以看到，这种方式就是一个回调套一个回调函，套的太多了很容易写出 > 形状的代码；
### 遍历数组
在遍历数组时，使用某个函数一次对数据成员做一些处理也是常见的需求，如果函数是同步处理的，一般就会写出以下代码：
```
var len = arr.length,
    i = 0;
for(; i < len; ++i>){
    arr[i] = sync(arr[i]);
}
```
如果异步执行的，以上代码就无法保证循环结束后所有数组成员都处理完毕了，如果数组成员必须一个一个串行处理，则一般按照以下方式编写异步代码：
```
(function next(i, len, callback){
    if(i < len){
        async(arr[i], value => {
            arr[i] = value;
            next(i + 1, len, callback);
        });
    }
    else {
        callback();
    }
}(0, arr.length, () => {
    // All array items have processed
}))
```
可以看到，以上代码在异步函数 `执行一次` 并 `返回执行结果` 后才传入 `下一个数组成员` 并开始下一轮执行，直到所有数组成员处理完毕后，通过 `回调的方式` 触发后续代码执行。</br>
如果数组成员可以并行处理，但后续代码任然需要所有数组成员处理完毕后才能执行的话，则异步代码会调整成以下形式：
```
// 自执行一个函数
// *** 计数器变量 count ***
// *** 执行长度的变量 arr.length ***
(function next(i, len, count, callback){
    // 并行执行所有操作 数组项的函数
    // 这里应用的参数传值是复制的特性
    // 还使用了闭包
    for(; i < len; ++i){
        (function (i){
            // 异步操作的数组项，结束时更新了数组项，并判定是否操作完了所有数组项
            async(arr[i], value => {
                arr[i] = value;
                if(++count === len){
                    callback();
                }
            });
        }(i))
    }
}(0, arr.length, 0, () => {
    // All array items have processed
}))
```
可以看到，与异步串行遍历的版本相比，以上代码并行处理所有数组成员。并通过 `计数器变量` 来判定什么时候所有数组成员都处理完毕了
### 异常处理
JS自身提供的异常捕获和处理机制 -- `try..catch..`, 只能用于同步执行的代码，看案例：
```
function sync(fn){
    return fn();
}

try {
    sync(null);
    // Do something else ...
}
catch(err){
    console.log('Error: %s', err.message);
    // Do something with error msg ...
}

------ console -----------------------

Error: object is not a function
```
可以看到，异常会沿着代码执行路径一致冒泡，直到遇到第一个 `try` 语句是被捕获，但由于异步函数会 `打断` 代码 `执行路径`，异步函数在 `执行过程中` 以及 `执行之后` 产生的异常 `冒泡` 到 `执行路径` 被 `打断的位置` 时，如果一直没有遇到 `try` 语句，就作为一个 `全局异常` 抛出，看案例：
```
function async(fn, callback){
    // Code execution path breaks here.
    setTimeout(() => {
        callback(fn());
    }, 0);
}

try {
    async(null, data => {
        // Do Something ...
    });
}
catch (err){
    console.log('Error: %s', err.message);
}

-- Console ------------------------------
/home/user/test.js:4
        callback(fn());
                 ^
TypeError: object is not a function
    at null._onTimeout (/home/user/test.js:4:13)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```
因为代码执行路径被打断了，我们就需要在异常冒泡到断点之前用 `try` 语句把异常捕获住，并通过 `回调函数` 传递被捕获的异常，于是我们可以像下边这样改造上边的例子。
```
function async(fn, callback){
    // Code execution path breaks here.
    setTimeout(() => {
        try {
            callback(null, fn());
        }
        catch (err){
            callback(err);
        }
    }, 0);
}

async(null, (err, data) => {
    if(err){
        // Do Something with error ...
    }
    else {
        // Do Something with data ...
    }
});
```
可以看到，异常再次被捕获住了，在 NodeJS 中，几乎所有异步API都按照以上方式设计，回调函数第一个参数都是 err,因此我们再编写自己的异步函数时，也可以按照这种方式来处理异常，，与 NodeJS 的设计风格保持一致。</br>
有了异常处理方式后，我接着可以想一想一般我们是怎么写代码的。基本上，我们的代码都是做一些事情，然后调用一个函数，然后再做一些事情，然后再调用一个函数，如何循环，如果我们写的是同步代码，只需要在代码入口点写一个 try 语句就能捕获所有冒泡上来的异常，看案例：
```
function main(){
    // Do Something ..
    syncA();

    // Do Something ..
    syncB();
    
    // Do Something ..
    syncC();
}

try{
    main();
}
catch(err){
    // Deal with exception ...
}
```
但是，如果我们写的是异步代码，就只有呵呵了。由于每次异步函数调用都会打断代码执行路径，只能通过回调函数来传递异常，于是我们就需要在每个回调函数里判断是否有异常发生，于是只用三次异步函数调用，就会产生下边这种代码：
```
function main(callback){
    // Do Something ..
    syncA((err, data) => {
        if(err){
            callback(err)
        }
        else {
            // Do Something ..
            syncB((err, data) => {
                if(err){
                    callback(err)
                }
                else {
                    // Do Something ..
                    syncC((err, data) => {
                        if(err){
                            callback(err)
                        }
                        else {
                            callback(null)
                        }
                    });
                }
            });
        }
    });
}

main(err => { 
    if(err) {
        // Do something with error ... 
    }
    // Do something else ...
});
```
可以看到，回调函数已经让代码变得复杂了。而异步方式下对异常的处理更加剧了代码的复杂度，如果NodeJS的最大卖点最后变成这个样子，那就没人愿意用 NodeJS 了，因此接下来会介绍 NodeJS 提供的解决方案。
## 域（Domain）


### 陷阱



